version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_THE_GUARDIAN_API_KEY=${VITE_THE_GUARDIAN_API_KEY}
      - VITE_NEW_YORK_TIMES_API_KEY=${VITE_NEW_YORK_TIMES_API_KEY} 